### PR TITLE
Fix widget panel visibility in dashboard designer

### PR DESCRIPTION
**Pull request by pahans**
## Purpose
Fix widget panel visibility in dashboard designer
Fixes https://github.com/wso2/analytics-apim/issues/668

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by TanyaM** [comment]
Shall we add an ellipsis after a certain number of characters and show the long name when hovered. 
If we go with your approach, when the widget name is very long, there will be lot of empty spaces below the adjoined listing.

**Comment by pahans** [comment]
@TanyaM We cant add ellipsis based on a number of characters or based on height.

**Comment by TanyaM** [comment]
> @TanyaM We cant add ellipsis based on a number of characters or based on height.

Widget name is set here in a div [1]
Can't we change this to a Text element and use numberOfLines or use css ( ex: white-space: nowrap; overflow: hidden; text-overflow: ellipsis;) kind of approach?

Could you please explain the technical limitation.

[1] https://github.com/wso2/carbon-dashboards/blob/master/components/dashboards-web-component/src/designer/components/WidgetCard.jsx#L77

**Comment by TanyaM** [comment]
@pahans: AFAIK Its not that complex 
<Text numberOfLines={1}>long long long long text<Text>
Even if its complex, IMO that is worth from UX point of view.
@erangatl  WDYT?

**Comment by erangatl** [comment]
> @pahans: AFAIK Its not that complex
> `<Text numberOfLines={1}>long long long long text<Text>`
> Even if its complex, IMO that is worth from UX point of view.
> @erangatl WDYT?

+1 to have same size thumbnails and use multiline ellipsis

**Comment by pahans** [comment]
> @pahans: AFAIK Its not that complex
> `<Text numberOfLines={1}>long long long long text<Text>`
Having one line of text is too short IMO, most widget titles will look like "APIM Api ..." and it will be harder to differentiate. 

> Even if its complex, IMO that is worth from UX point of view.
> @erangatl WDYT?

**Comment by erangatl** [comment]
> > @pahans: AFAIK Its not that complex
> > `<Text numberOfLines={1}>long long long long text<Text>`
> 
> Having one line of text is too short IMO, most widget titles will look like "APIM Api ..." and it will be harder to differentiate.
> 
> > Even if its complex, IMO that is worth from UX point of view.
> > @erangatl WDYT?

Yes we need at least two line ellipsis

**Comment by pahans** [comment]
as I mentioned in a previous comment in order to maintain the same size thumbnails, We could try to add ellipsis based on the number of lines. If that approach fails let's move to a javascript solution.
@TanyaM WDYT

**Comment by pahans** [comment]
Used the javascript approach. There is no very straightforward cross browser compatible way to achieve multiline truncation in CSS. http://hackingui.com/front-end/a-pure-css-solution-for-multiline-text-truncation/

**Pull request merged**
